config/routes.rb
Rails.application.routes.draw do
  
  root :to => "pages#home"

  get "staffer_tasks" => "pages#index", :as => "staffer_tasks"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "activate" => "users#activate", :as => "activate"
  get "suspend" => "users#suspend", :as => "suspend"

  get "tasks/update_users" => "tasks#update_users", :as => "update_users"

  resources :users
  resources :sessions
  resources :tasks
  resources :teams
  resources :updates

end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
	validates :user_id, presence: true
	validates :manager_id, presence: true
	
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new

		@task = Task.new

    if current_user.teams != []

      team = current_user.teams[0]
      
      @users = team.users.where(:access => 3).where(:active => true)

    else

      @users = User.where(:active => true)
      
    end  

	end

  def update_users

    # updates users based on team selected
    team = Team.find(params[:team_id])
    # map to email and id for use in our options_for_select
    @users = team.users.where(:access => 3).where(:active => true).map{|a| [a.email, a.id]}.insert(0, "")

  end

	def create

		@task = Task.new(task_params)

    if current_user.teams != []
      team = current_user.teams[0]
      @users = team.users.where(:access => 3).where(:active => true)
    else
      @users = User.where(:active => true)
    end

		if @task.save	
			redirect_to tasks_path, :notice => "New Task Assigned!"
		else
			render "new"
		end

	end

	def edit

    	@task = Task.find(params[:id])

      if current_user.teams != []

        team = current_user.teams[0]
        
        @users = team.users.where(:access => 3).where(:active => true)

      else

        @users = User.where(:active => true)

      end  

	end

	def update

  	@task = Task.find(params[:id])
 
  	if @task.update(task_params)
    		redirect_to tasks_path, :notice => "Task Updated!"
  	else
    		render "edit"
  	end

	end

  def index

    if current_user.access == 1

      @tasks = Task.all

    elsif current_user.access == 2

      @tasks = []

      Task.all.each do |x|
        manager = User.where(:id => x.manager_id)[0]

        if (manager.teams != []) && (manager.teams[0].id == current_user.teams[0].id)
          @tasks << x
        end
      end

    else

      @tasks = Task.where(:user_id => current_user.id)
      
    end

  end

  def show

    @task = Task.find(params[:id])

    @updates = Update.where(:task_id => @task.id)

  end

  def destroy

    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, :notice => "Task deleted!"

  end


	private
  	
    ## Strong Parameters 
  	def task_params

    	params.require(:task).permit(:id, :title, :body, :user_id, :manager_id)
      
  	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_new.html.erb
<%= stylesheet_link_tag    "custom", media: "all" %>

<div class="row-fluid">
	<div class="col-md-4 well center">	
		<%= form_for @task, :html => {:class => "form-horizontal"} do |f| %>
			<% if @task.errors.any? %>
				
				<div class="alert alert-info" role="alert">
					<span><%= @task.errors.full_messages[0] %></span>
				</div>

			<% end %>
		
			<fieldset>

				<% if @task.persisted? %>
					<legend>Edit Task</legend>
				<% else%>
					<legend>Create Task</legend>
				<% end %>

				<div class="control-group">	

					<%= f.label :title %><br />

					<div class="controls">
						<%= f.text_field :title, :class => "form-control" %>
					</div>

				</div>

				<div class="control-group">	

					<%= f.label :body %><br />

					<div class="controls">
						<%= f.text_area :body, :class => "form-control" %>
					</div>
					
				</div>

				<% if current_user && current_user.access == 1 %>

					<% teams = Team.all %>

					<div class="control-group">

						<label>Team</label><br />

						<select class="team_select">

							<option value=""></option>

							<% teams.each do |x| %>
								<option value="<%= x.id %>"><%= x.name%></option>
							<% end %>

						</select>

					</div>
					
				<% end %>
          	 	
          	 	<div class="control-group">	
					<%= f.label :user_id, "Staffer to assign task to." %><br />
					<%= f.collection_select :user_id, @users, :id, :email, include_blank: true %>
				</div>

				<%= f.hidden_field :manager_id, :value => current_user.id %>

				<div class="form-actions sub">
					<%= f.submit :class => "btn btn-primary" %>
				</div>

			</fieldset>
			
		<% end %>

	</div>
</div>

app/views/tasks/edit.html.erb
<%= render partial: "new" %>

app/views/tasks/index.html.erb
	<div class="row">

	    <div class="col-lg-12">
	        <h1 class="page-header">Tasks</h1>
	    </div>
	    
	</div>

	<p><%= link_to "Assign New Task", new_task_path %></p>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
		        <th>Title</th>
		        <th>Staffer</th>
		        <th>Manager</th>
		        <th></th>
		        <th></th>
		        <th></th>
			</tr>
		</thead>

		<% i=0 %>
		<tbody>

			<% @tasks.each do |task| %>
			
				<% i = i + 1 %>
				<% staffer = User.find(task.user_id) %>
				<% manager = User.find(task.manager_id) %>

				<tr>
					
					<td>
						<%= "#{i}" %>
					</td>

		        	<td>
		        		<%= task.title %>
		        	</td>

		        	<td>
		        		<%= staffer.email %>
					</td>

					<td>
		        		<%= manager.email %>
					</td>

					<td>
						<%= link_to "View", task_path(task) %>
					</td>

					<td>
						<%= link_to "Edit", edit_task_path(task) %>
					</td>

					<td>
						<%= link_to "Destroy", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
					</td>

				</tr>

			<% end %>

		</tbody>
	</table>

app/views/tasks/new.html.erb
<%= render partial: "new" %>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag    "custom", media: "all" %>

<div class="row-fluid">
	<div class="col-md-4 well center">	
		<fieldset>
			<legend>Title: <%= @task.title %></legend>

			<div class="control-group">	

				<p>Description: <%= @task.body %></p>	

			</div>
		</fieldset>
	</div>
</div>

<% i=0 %>

<h3>Updates</h3>

<% if current_user.access == 3 %>

	<%= link_to "Add new Update", new_update_path(task_id: @task.id) %>

<% end %>

<table class="table table-hover">

	<thead>
		<tr>
			<th>#</th>
	        <th>Title</th>
	        <th>Body</th>
	        <th>Staffer</th>
	        <th>Update Time</th>
		</tr>
	</thead>

	<tbody>

		<% @updates.each do |x| %>
		
			<% i = i + 1 %>

			<tr>
				
				<td>
					<%= "#{i} - " %>
				</td>

	        	<td>
	        		<%= x.title %>
	        	</td>

	        	<td>
	        		<%= x.body %>
				</td>

				<td>
	        		<%= User.where(:id => x.user_id)[0].email %>
				</td>

				<td>
	        		<%= x.created_at.strftime("%m/%d/%Y %I:%M %p") %>
				</td>
			</tr>

		<% end %>
	</tbody>

</table>



	

app/views/tasks/update_users.js.erb
$("#task_user_id").html("<%= escape_javascript(options_for_select(@users)) %>");