config/routes.rb
Rails.application.routes.draw do
  
  root :to => "pages#home"

  get "staffer_tasks" => "pages#index", :as => "staffer_tasks"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "activate" => "users#activate", :as => "activate"
  get "suspend" => "users#suspend", :as => "suspend"

  get "tasks/update_users" => "tasks#update_users", :as => "update_users"

  resources :users
  resources :sessions
  resources :tasks
  resources :teams
  resources :updates

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :memberships, :foreign_key => :user_id, :primary_key => :id, :dependent => :destroy
  has_many :teams, :through => :memberships
  has_many :tasks, :dependent => :destroy
  has_many :updates, :dependent => :destroy

  accepts_nested_attributes_for :memberships

	attr_accessor :password

	before_save :encrypt_password

  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_uniqueness_of :email
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	

	def self.authenticate(email, password)

    	user = find_by_email(email)

    	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      		user
    	else
      		nil
    	end
      
	end

	def encrypt_password

    	if password.present?
      		self.password_salt = BCrypt::Engine.generate_salt
      		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    	end

  end

  def suspend
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :user_restrict

	def new

		@user = User.new
		@user.memberships.build	

	end

	def create

		@user = User.new(user_params)

		if @user.save
			redirect_to users_path, :notice => "New Account Created!"
		else
			render "new"
		end

	end

	def edit

    	@user = User.find(params[:id])

  	end

  	def update

    	@user = User.find(params[:id])
 
    	if @user.update(user_params)
      		redirect_to users_path, :notice => "Account Updated!"
    	else
      		render "edit"
    	end

  	end


	def destroy

  		@user = User.find(params[:id])
  		@user.destroy
 
  		redirect_to users_path, :notice => "Account deleted!"

	end

	def index

		if current_user.access == 1	
  			@accounts = User.all
		else
  			@staffers = User.where(:access => 3)
  		end

	end

	def activate

		@user = User.find(params[:format])

		@user.update_attributes(:active => true)

		redirect_to users_path, :notice => "Account Activated!"

	end

	def suspend

		@user = User.find(params[:format])

		@user.update_attributes(:active => false)

		redirect_to users_path, :notice => "Account Suspended!"

	end

	private
  	
	  	## Strong Parameters 
		def user_params

	    	params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :manager, :access, memberships_attributes: [:id, :team_id, :user_id])

	  	end

	  	def user_restrict

	  		unless current_user && current_user.access < 3
	  			redirect_to root_path
	  		end

	  	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<%= stylesheet_link_tag    "custom", media: "all" %>

<div class="row-fluid">
	<div class="col-md-4 well center">	

	  	<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
			<% if @user.errors.any? %>
				<div class="alert alert-info" role="alert">
					<span><%= @user.errors.full_messages[0] %></span>
				</div>
			<% end %>

			<fieldset>

				<% if @user.persisted? %>
					<legend>Edit Account</legend>
				<% else%>
					<legend>Create Account</legend>
				<% end %>

				<div class="control-group">			

					<%= f.label :email %>

					<div class="controls">
						<%= f.text_field :email, :class => "form-control" %>
					</div>
					
				</div>

				<div class="control-group">			

					<%= f.label :first_name %>

					<div class="controls">
						<%= f.text_field :first_name, :class => "form-control" %>
					</div>
					
				</div>

				<div class="control-group">			

					<%= f.label :last_name %>

					<div class="controls">
						<%= f.text_field :last_name, :class => "form-control" %>
					</div>
					
				</div>

				<div class="control-group">	

					<%= f.label :password %>

					<div class="controls">
						<%= f.password_field :password, :class => "form-control" %>
					</div>
				</div>

				<div class="control-group">	

					<%= f.label :password_confirmation %>

					<div class="controls">
						<%= f.password_field :password_confirmation, :class => "form-control" %>
					</div>
				</div>

				<% if current_user && current_user.access == 1 %>
					<div class="control-group">	

						<%= f.label(:access, "User Access Level") %><br />

						<select name="user[access]" class="controls">
							<option></option>
					  		<option value="1">SuperManager</option>
				  			<option value="2">Manager</option>
			  				<option value="3">Staffer</option>
						</select> 

					</div>

					<%= f.fields_for :memberships do |b| %>

						<div class="control-group">	

				    		<%= b.label :team_id, "Assign account to a team." %><br />

				    		<div class="controls">
								<%= b.collection_select :team_id, Team.order(:id),:id,:name, include_blank: true %>
							</div>

						</div>

			  		<% end %>

				<% else %>

					<%= f.fields_for :memberships do |b| %>

						<%= b.hidden_field :team_id, :value => current_user.teams[0].id %>

			  		<% end %>

					<%= f.hidden_field :access, :value => 3 %>

					
				<% end %>


				<div class="form-actions sub">
					<%= f.submit :class => "btn btn-primary" %>
				</div>

			</fieldset>

		<% end %>

	</div>
</div>

app/views/users/edit.html.erb
<%= render partial: "new" %>

app/views/users/index.html.erb
<% level = { 1 => 'SuperManager', 2 => 'Manager', 3 => 'Staffer' } %>



<div class="row">

    <div class="col-sm-12">
        <h1 class="page-header">Accounts</h1>
    </div>
</div>   

<div class="row">
    <div class="col-sm-12">
        <p><%= link_to "Add new Account", sign_up_path %></p> 
             
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Email</th>
                    <th>Team</th>
                    <th>Role</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <% if current_user.access == 1 %>

            <% i=0 %>

            <% @accounts.each do |acc| %>

                <% i = i + 1 %>

                <tr>
                    
                    <td>
                        <%= "#{i}" %>
                    </td>

                    <td>
                        <%= acc.email %> 
                    </td>

                    <% if acc.teams != [] %>
                        <td>
                            <%= acc.teams[0].name %> 
                        </td>
                    <% else %>
                        <td>N/A </td>
                    <% end %>

                    <td>
                        <%= level[acc.access]%>
                    </td>

                    <td>
                        <%= link_to "Edit", edit_user_path(acc) %>
                    </td>

                    <td>
                        <%= link_to "Destroy", user_path(acc), method: :delete,data: { confirm: "Are you sure?" } %>
                    </td>

                    <% if acc.active %>
                        <td>
                            <%= link_to "Suspend", suspend_path(acc), data: { confirm: "Are you sure?" } %>
                        </td>
                    <% else %>
                        <td>
                            <%= link_to "Activate", activate_path(acc), data: { confirm: "Are you sure?" } %>
                        </td>
                    <% end %>

                </tr>

            <% end %>

            <% else %>

            <% i=0 %>

            <% @staffers.each do |acc| %>

                <% i = i + 1 %>

                <% if (acc.teams != []) && (acc.teams[0].id == current_user.teams[0].id) %>

                    <tr>
                        
                        <td>
                            <%= "#{i}" %>
                        </td>

                        <td>
                            <%= acc.email %> 
                        </td>

                        <% if acc.teams != [] %>
                            <td>
                                <%= acc.teams[0].name %> 
                            </td>
                        <% else %>
                            <td>N/A </td>
                        <% end %>

                        <td>
                            <%= level[acc.access]%>
                        </td>

                        <td>
                            <%= link_to "Edit", edit_user_path(acc) %>
                        </td>

                        <td>
                            <%= link_to "Destroy", user_path(acc), method: :delete,data: { confirm: "Are you sure?" } %>
                        </td>

                        <% if acc.active %>
                            <td>
                                <%= link_to "Suspend", suspend_path(acc), data: { confirm: "Are you sure?" } %>
                            </td>
                        <% else %>
                            <td>
                                <%= link_to "Activate", activate_path(acc), data: { confirm: "Are you sure?" } %>
                            </td>
                        <% end %>

                    </tr>

                <% end %>

            <% end %>

            <% end %>
            </tbody>
        </table>
    </div>
    
</div>

app/views/users/new.html.erb
<%= render partial: "new" %>