config/routes.rb
Rails.application.routes.draw do
  
  root :to => "pages#home"

  get "staffer_tasks" => "pages#index", :as => "staffer_tasks"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "activate" => "users#activate", :as => "activate"
  get "suspend" => "users#suspend", :as => "suspend"

  get "tasks/update_users" => "tasks#update_users", :as => "update_users"

  resources :users
  resources :sessions
  resources :tasks
  resources :teams
  resources :updates

end

app/views/pages/_manager_dash.html.erb
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @users.count %></div>
                                    <div>Accounts!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                            	<%= link_to users_path do %>
                                	<span class="pull-left">View Details</span>
                                	<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                	<div class="clearfix"></div>
                            	<% end %>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @tasks.count %></div>
                                    <div>Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                            	<%= link_to tasks_path do %>
	                                <span class="pull-left">View Details</span>
	                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                                <div class="clearfix"></div>
                                <% end %>
                            </div>
                        </a>
                    </div>
                </div>
                
            </div>

app/views/pages/_staffer_dash.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @tasks.count %></div>
                        <div>Tasks!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                	<%= link_to staffer_tasks_path do %>
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    <% end %>
                </div>
            </a>
        </div>
    </div>
    
</div>

app/views/pages/_super_manager_dash.html.erb
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @users.count %></div>
                                    <div>Accounts!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                            	<%= link_to users_path do %>
                                	<span class="pull-left">View Details</span>
                                	<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                	<div class="clearfix"></div>
                            	<% end %>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= @tasks.count %></div>
                                    <div>Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                            	<%= link_to tasks_path do %>
	                                <span class="pull-left">View Details</span>
	                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                                <div class="clearfix"></div>
                                <% end %>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%= Team.all.count %></div>
                                    <div>Teams!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                            	<%= link_to teams_path do %>
	                                <span class="pull-left">View Details</span>
	                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
	                                <div class="clearfix"></div>
                                <% end %>
                            </div>
                        </a>
                    </div>
                </div>
                
            </div>

app/views/pages/_tasks.html.erb
<div class="row">

    <div class="col-lg-12">
        <h1 class="page-header">Tasks</h1>
    </div>
    
</div>

<table class="table table-hover">
	<thead>
		<tr>
			<th>#</th>
	        <th>Title</th>
	        <th>Staffer</th>
	        <th>Manager</th>
	        <th></th>
	        <th></th>
		</tr>
	</thead>

	<% i=0 %>
	<tbody>

		<% @tasks.each do |task| %>
		
			<% i = i + 1 %>
			<% staffer = User.find(task.user_id) %>
			<% manager = User.find(task.manager_id) %>

			<tr>
				
				<td>
					<%= "#{i}" %>
				</td>

	        	<td>
	        		<%= task.title %>
	        	</td>

	        	<td>
	        		<%= staffer.email %>
				</td>

				<td>
	        		<%= manager.email %>
				</td>

				<td>
					<%= link_to "View", task_path(task) %>
				</td>

			</tr>

		<% end %>
		
	</tbody>
</table>

app/views/pages/home.html.erb
<% if current_user %>

	<% if current_user.access == 1 %>

		<%= render partial: "super_manager_dash" %>

	<% elsif current_user.access == 2 %>

		<%= render partial: "manager_dash" %>

	<% else %>

		<%= render partial: "staffer_dash" %>		

	<% end %>

<% else %>
	
	<%= render :partial => "sessions/new" %>

<% end %>