config/routes.rb
Rails.application.routes.draw do
  
  root :to => "pages#home"

  get "staffer_tasks" => "pages#index", :as => "staffer_tasks"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  get "activate" => "users#activate", :as => "activate"
  get "suspend" => "users#suspend", :as => "suspend"

  get "tasks/update_users" => "tasks#update_users", :as => "update_users"

  resources :users
  resources :sessions
  resources :tasks
  resources :teams
  resources :updates

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>TaskManager</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  </head>

  <body>

    <div id="wrapper">
      <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to "Task Manager", root_path, class:"navbar-brand" %>
          </div>
          <!-- /.navbar-header -->
          <% if current_user %>
            <ul class="nav navbar-top-links navbar-right">
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <% if current_user %>
                          <li>
                            <%= link_to root_path do %>

                              <i class="fa fa-user fa-fw"></i><%= current_user.email %>

                            <% end %>
                          </li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to log_out_path do %>

                              <i class="fa fa-sign-out fa-fw"></i>Logout

                            <% end %>
                          </li>
                        <% else %>
                          <li>
                            <%= link_to log_in_path do %>

                              <i class="fa fa-sign-out fa-fw"></i>Login

                            <% end %>
                          </li>
                        <% end %>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
          <!-- /.navbar-top-links -->
          
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                      <% if current_user %>
                        <li>
                          <%= link_to root_path do %>
                            <i class="fa fa-dashboard fa-fw"></i> Dashboard
                          <% end %>
                        </li>
                      <% end %>

                      <% if current_user && current_user.access == 1 %>

                        <li>
                          <%= link_to users_path do %>
                            <i class="fa fa-user fa-fw"></i> Accounts
                          <% end %>
                        </li>
                        
                        <li>
                          <%= link_to tasks_path do %>
                            <i class="fa fa-tasks fa-fw"></i> Tasks
                          <% end %>
                        </li>
                        <li>
                          <%= link_to teams_path do %>
                            <i class="fa fa-users fa-fw"></i> Teams
                          <% end %>
                        </li>

                      <% elsif current_user && current_user.access == 2 %>
                        <li>
                          <%= link_to users_path do %>
                            <i class="fa fa-user fa-fw"></i> Accounts
                          <% end %>
                        </li>
                        
                        <li>
                          <%= link_to tasks_path do %>
                            <i class="fa fa-tasks fa-fw"></i> Tasks
                          <% end %>
                        </li>

                      <% else %>
                        <% if current_user && current_user.access == 3%>
                          <li>
                            <%= link_to staffer_tasks_path do %>
                              <i class="fa fa-tasks fa-fw"></i> Tasks
                            <% end %>
                          </li>
                        <% end %>

                      <% end %>   
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
          <% end %>
          <!-- /.navbar-static-side -->
      </nav>
    </div>

    <% if current_user %>

      <div id="page-wrapper">

        <% flash.each do |name, msg| %>

          <div class="container">
            <div class="row">
              <div class="alert alert-info span4 offset4" role="alert">
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            </div>  
          </div>    
      
        <% end %>

        <%= yield %>

      </div>

    <% else %>

      <%= stylesheet_link_tag    "custom", media: "all" %>

      <% flash.each do |name, msg| %>

          <div class="container">
            <div class="row">
              <div class="alert alert-info span4 offset4" role="alert">
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            </div>  
          </div>    
      
        <% end %>

      <%= yield  %>

    <% end %>


  	
    
  </body>

</html>